apiVersion: apps/v1
kind: Deployment
metadata:
  name: regexprocessor
  labels:
    app: regexprocessor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: regexprocessor
  template:
    metadata:
      labels:
        app: regexprocessor
    spec:
      containers:
      - name: regexprocessor
        image: israelhercam/regexprocessor-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"