apiVersion: apps/v1
kind: Deployment
metadata:
  name: espublisher
  labels:
    app: espublisher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: espublisher
  template:
    metadata:
      labels:
        app: espublisher
    spec:
      containers:
      - name: espublisher
        image: israelhercam/espublisher-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"