apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-processor
  labels:
    app: sql-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-processor
  template:
    metadata:
      labels:
        app: sql-processor
    spec:
      containers:
      - name: sql-processor
        image: notthatdude/sql-processor