apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlprocessor
  labels:
    app: sqlprocessor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sqlprocessor
  template:
    metadata:
      labels:
        app: sqlprocessor
    spec:
      containers:
      - name: sqlprocessor
        image: israelhercam/sqlprocessor-image
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"